#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access_Layer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="H_Desk_Database")]
	public partial class DataConDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEmp_Detail(Emp_Detail instance);
    partial void UpdateEmp_Detail(Emp_Detail instance);
    partial void DeleteEmp_Detail(Emp_Detail instance);
    partial void InsertEmp_Table(Emp_Table instance);
    partial void UpdateEmp_Table(Emp_Table instance);
    partial void DeleteEmp_Table(Emp_Table instance);
    partial void InsertRoom_No_Table(Room_No_Table instance);
    partial void UpdateRoom_No_Table(Room_No_Table instance);
    partial void DeleteRoom_No_Table(Room_No_Table instance);
    partial void InsertAppointment_Table(Appointment_Table instance);
    partial void UpdateAppointment_Table(Appointment_Table instance);
    partial void DeleteAppointment_Table(Appointment_Table instance);
    #endregion
		
		public DataConDataContext() : 
				base(global::Data_Access_Layer.Properties.Settings.Default.H_Desk_DatabaseConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataConDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataConDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataConDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataConDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Emp_Detail> Emp_Details
		{
			get
			{
				return this.GetTable<Emp_Detail>();
			}
		}
		
		public System.Data.Linq.Table<Emp_Table> Emp_Tables
		{
			get
			{
				return this.GetTable<Emp_Table>();
			}
		}
		
		public System.Data.Linq.Table<Room_No_Table> Room_No_Tables
		{
			get
			{
				return this.GetTable<Room_No_Table>();
			}
		}
		
		public System.Data.Linq.Table<Appointment_Table> Appointment_Tables
		{
			get
			{
				return this.GetTable<Appointment_Table>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Emp_Details")]
	public partial class Emp_Detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Emp_Id;
		
		private System.Nullable<byte> _Curr_Status;
		
		private string _Notice;
		
		private System.Nullable<System.DateTime> _Given_Date;
		
		private System.Nullable<System.TimeSpan> _Given_Time;
		
		private string _IP_Address;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmp_IdChanging(int value);
    partial void OnEmp_IdChanged();
    partial void OnCurr_StatusChanging(System.Nullable<byte> value);
    partial void OnCurr_StatusChanged();
    partial void OnNoticeChanging(string value);
    partial void OnNoticeChanged();
    partial void OnGiven_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnGiven_DateChanged();
    partial void OnGiven_TimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OnGiven_TimeChanged();
    partial void OnIP_AddressChanging(string value);
    partial void OnIP_AddressChanged();
    #endregion
		
		public Emp_Detail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Emp_Id
		{
			get
			{
				return this._Emp_Id;
			}
			set
			{
				if ((this._Emp_Id != value))
				{
					this.OnEmp_IdChanging(value);
					this.SendPropertyChanging();
					this._Emp_Id = value;
					this.SendPropertyChanged("Emp_Id");
					this.OnEmp_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Curr_Status", DbType="TinyInt")]
		public System.Nullable<byte> Curr_Status
		{
			get
			{
				return this._Curr_Status;
			}
			set
			{
				if ((this._Curr_Status != value))
				{
					this.OnCurr_StatusChanging(value);
					this.SendPropertyChanging();
					this._Curr_Status = value;
					this.SendPropertyChanged("Curr_Status");
					this.OnCurr_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notice", DbType="VarChar(50)")]
		public string Notice
		{
			get
			{
				return this._Notice;
			}
			set
			{
				if ((this._Notice != value))
				{
					this.OnNoticeChanging(value);
					this.SendPropertyChanging();
					this._Notice = value;
					this.SendPropertyChanged("Notice");
					this.OnNoticeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Given_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Given_Date
		{
			get
			{
				return this._Given_Date;
			}
			set
			{
				if ((this._Given_Date != value))
				{
					this.OnGiven_DateChanging(value);
					this.SendPropertyChanging();
					this._Given_Date = value;
					this.SendPropertyChanged("Given_Date");
					this.OnGiven_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Given_Time", DbType="Time")]
		public System.Nullable<System.TimeSpan> Given_Time
		{
			get
			{
				return this._Given_Time;
			}
			set
			{
				if ((this._Given_Time != value))
				{
					this.OnGiven_TimeChanging(value);
					this.SendPropertyChanging();
					this._Given_Time = value;
					this.SendPropertyChanged("Given_Time");
					this.OnGiven_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP_Address", DbType="VarChar(20)")]
		public string IP_Address
		{
			get
			{
				return this._IP_Address;
			}
			set
			{
				if ((this._IP_Address != value))
				{
					this.OnIP_AddressChanging(value);
					this.SendPropertyChanging();
					this._IP_Address = value;
					this.SendPropertyChanged("IP_Address");
					this.OnIP_AddressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Emp_Table")]
	public partial class Emp_Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _Phone;
		
		private string _Email;
		
		private string _Address;
		
		private System.Nullable<bool> _Gender;
		
		private string _Qualification;
		
		private System.Data.Linq.Binary _Image;
		
		private string _Password;
		
		private System.Nullable<bool> _Admin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnGenderChanging(System.Nullable<bool> value);
    partial void OnGenderChanged();
    partial void OnQualificationChanging(string value);
    partial void OnQualificationChanged();
    partial void OnImageChanging(System.Data.Linq.Binary value);
    partial void OnImageChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnAdminChanging(System.Nullable<bool> value);
    partial void OnAdminChanged();
    #endregion
		
		public Emp_Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(13)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(500)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Bit")]
		public System.Nullable<bool> Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qualification", DbType="VarChar(500)")]
		public string Qualification
		{
			get
			{
				return this._Qualification;
			}
			set
			{
				if ((this._Qualification != value))
				{
					this.OnQualificationChanging(value);
					this.SendPropertyChanging();
					this._Qualification = value;
					this.SendPropertyChanged("Qualification");
					this.OnQualificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin", DbType="Bit")]
		public System.Nullable<bool> Admin
		{
			get
			{
				return this._Admin;
			}
			set
			{
				if ((this._Admin != value))
				{
					this.OnAdminChanging(value);
					this.SendPropertyChanging();
					this._Admin = value;
					this.SendPropertyChanged("Admin");
					this.OnAdminChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Room_No_Table")]
	public partial class Room_No_Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Room_No;
		
		private System.Nullable<int> _Emp_Id;
		
		private bool _Reserved;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoom_NoChanging(int value);
    partial void OnRoom_NoChanged();
    partial void OnEmp_IdChanging(System.Nullable<int> value);
    partial void OnEmp_IdChanged();
    partial void OnReservedChanging(bool value);
    partial void OnReservedChanged();
    #endregion
		
		public Room_No_Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room_No", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Room_No
		{
			get
			{
				return this._Room_No;
			}
			set
			{
				if ((this._Room_No != value))
				{
					this.OnRoom_NoChanging(value);
					this.SendPropertyChanging();
					this._Room_No = value;
					this.SendPropertyChanged("Room_No");
					this.OnRoom_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Id", DbType="Int")]
		public System.Nullable<int> Emp_Id
		{
			get
			{
				return this._Emp_Id;
			}
			set
			{
				if ((this._Emp_Id != value))
				{
					this.OnEmp_IdChanging(value);
					this.SendPropertyChanging();
					this._Emp_Id = value;
					this.SendPropertyChanged("Emp_Id");
					this.OnEmp_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reserved", DbType="Bit NOT NULL")]
		public bool Reserved
		{
			get
			{
				return this._Reserved;
			}
			set
			{
				if ((this._Reserved != value))
				{
					this.OnReservedChanging(value);
					this.SendPropertyChanging();
					this._Reserved = value;
					this.SendPropertyChanged("Reserved");
					this.OnReservedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Appointment_Table")]
	public partial class Appointment_Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _A_Id;
		
		private string _Name;
		
		private string _Phone;
		
		private string _Email;
		
		private string _Purpose;
		
		private string _FeedBack;
		
		private System.Nullable<System.DateTime> _Req_Date;
		
		private System.Nullable<System.DateTime> _Date;
		
		private string _Time;
		
		private System.Nullable<int> _Emp_Id;
		
		private System.Nullable<bool> _Seen;
		
		private System.Nullable<bool> _Accept;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnA_IdChanging(int value);
    partial void OnA_IdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPurposeChanging(string value);
    partial void OnPurposeChanged();
    partial void OnFeedBackChanging(string value);
    partial void OnFeedBackChanged();
    partial void OnReq_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnReq_DateChanged();
    partial void OnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateChanged();
    partial void OnTimeChanging(string value);
    partial void OnTimeChanged();
    partial void OnEmp_IdChanging(System.Nullable<int> value);
    partial void OnEmp_IdChanged();
    partial void OnSeenChanging(System.Nullable<bool> value);
    partial void OnSeenChanged();
    partial void OnAcceptChanging(System.Nullable<bool> value);
    partial void OnAcceptChanged();
    #endregion
		
		public Appointment_Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int A_Id
		{
			get
			{
				return this._A_Id;
			}
			set
			{
				if ((this._A_Id != value))
				{
					this.OnA_IdChanging(value);
					this.SendPropertyChanging();
					this._A_Id = value;
					this.SendPropertyChanged("A_Id");
					this.OnA_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Purpose", DbType="VarChar(500)")]
		public string Purpose
		{
			get
			{
				return this._Purpose;
			}
			set
			{
				if ((this._Purpose != value))
				{
					this.OnPurposeChanging(value);
					this.SendPropertyChanging();
					this._Purpose = value;
					this.SendPropertyChanged("Purpose");
					this.OnPurposeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeedBack", DbType="VarChar(500)")]
		public string FeedBack
		{
			get
			{
				return this._FeedBack;
			}
			set
			{
				if ((this._FeedBack != value))
				{
					this.OnFeedBackChanging(value);
					this.SendPropertyChanging();
					this._FeedBack = value;
					this.SendPropertyChanged("FeedBack");
					this.OnFeedBackChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Req_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Req_Date
		{
			get
			{
				return this._Req_Date;
			}
			set
			{
				if ((this._Req_Date != value))
				{
					this.OnReq_DateChanging(value);
					this.SendPropertyChanging();
					this._Req_Date = value;
					this.SendPropertyChanged("Req_Date");
					this.OnReq_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="VarChar(10)")]
		public string Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this.OnTimeChanging(value);
					this.SendPropertyChanging();
					this._Time = value;
					this.SendPropertyChanged("Time");
					this.OnTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Id", DbType="Int")]
		public System.Nullable<int> Emp_Id
		{
			get
			{
				return this._Emp_Id;
			}
			set
			{
				if ((this._Emp_Id != value))
				{
					this.OnEmp_IdChanging(value);
					this.SendPropertyChanging();
					this._Emp_Id = value;
					this.SendPropertyChanged("Emp_Id");
					this.OnEmp_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seen", DbType="Bit")]
		public System.Nullable<bool> Seen
		{
			get
			{
				return this._Seen;
			}
			set
			{
				if ((this._Seen != value))
				{
					this.OnSeenChanging(value);
					this.SendPropertyChanging();
					this._Seen = value;
					this.SendPropertyChanged("Seen");
					this.OnSeenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accept", DbType="Bit")]
		public System.Nullable<bool> Accept
		{
			get
			{
				return this._Accept;
			}
			set
			{
				if ((this._Accept != value))
				{
					this.OnAcceptChanging(value);
					this.SendPropertyChanging();
					this._Accept = value;
					this.SendPropertyChanged("Accept");
					this.OnAcceptChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
